<a href="https://colab.research.google.com/github/jaekyoungkim/floor_DL/blob/main/%EB%B0%91%EB%B0%94%EB%8B%A5%EB%B6%80%ED%84%B0%EC%8B%9C%EC%9E%91%ED%95%98%EB%8A%94%EB%94%A5%EB%9F%AC%EB%8B%9D2_ch1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
!git clone https://github.com/WegraLee/deep-learning-from-scratch-2.git

Cloning into 'deep-learning-from-scratch-2'...
remote: Enumerating objects: 606, done.
remote: Counting objects: 100% (8/8), done.
remote: Compressing objects: 100% (8/8), done.
remote: Total 606 (delta 1), reused 5 (delta 0), pack-reused 598
Receiving objects: 100% (606/606), 29.82 MiB | 33.19 MiB/s, done.
Resolving deltas: 100% (361/361), done.


# ch1. 신경망 복습 

In [ ]:
import numpy as np
x=np.array([1,2,3])
x.__class__

numpy.ndarray

In [ ]:
x.shape

(3,)

In [ ]:
x.ndim

1

In [ ]:
W= np.array([[1,2,3],[4,5,6]])

In [ ]:
W.shape

(2, 3)

In [ ]:
W.ndim

2

In [ ]:
a=np.array([1,2,3])
b=np.array([4,5,6])
np.dot(a,b) # 벡터의 내적

32

In [ ]:
A=np.array([[1,2],[3,4]])
B=np.array([4,5,6])

In [ ]:
np.dot(A,B) 

array([[19, 22],
       [43, 50]])

In [ ]:
A=np.array([[1,2],[3,4]])
B=np.array([[5,6],[7,8]])

In [ ]:
np.matmul(A,B)  # 행렬곱

array([[19, 22],
       [43, 50]])

In [ ]:
# 100 NUMPY EXCERSICE 예제 해보기, 좋은 샘플임

In [ ]:
# 신경명에서 수행하는 작업 : 학습과 추론
# 입력층, 출력층, 은닉층으로 구성됨
# 가중치, 편향을 통해 계산됨


In [ ]:
# h(1x4) = x(1x2)W(2x4) + b(1x4)
# h1 = x1 * w11 + x2w21 + b1
# x : 입력
# h: 은닉층 뉴런
# W : 가중치
# b: 편향

In [1]:
import numpy as np
W1  = np.random.randn(2,4) ; W1 # 2x4 # 

array([[ 1.21648767, -0.48698938, -0.55972081, -0.33360003],
       [-0.07943261,  0.33523018,  1.91602756,  0.49719856]])

In [2]:
b1 = np.random.randn(4); b1 # 편향 

array([ 0.09281632, -1.32468704,  0.1211265 ,  1.45028844])

In [3]:
x = np.random.randn(10,2) ;x  # 10개의 샘플 데이터 10x2

array([[-0.79263062, -0.75536546],
       [-0.96074454, -0.7729176 ],
       [ 0.27417157,  1.24564265],
       [-0.17863988, -0.25924527],
       [-1.5889804 ,  0.12993258],
       [ 0.79132852, -0.05668989],
       [ 2.02010822,  0.22829108],
       [ 1.57134666, -0.50833922],
       [ 0.31941044, -0.37383323],
       [ 1.06823862,  0.33171146]])

In [6]:
h = np.matmul(x, W1)+b1 ; h # b1은 브로드캐스트됨, (4,) -> (10,4)로 복제됨
# 은닉층의 뉴런은 4개

array([[-0.8114084 , -1.19190565, -0.88252269,  1.33914341],
       [-1.01452271, -1.11591996, -0.8220562 ,  1.38649933],
       [ 0.327398  , -1.04062868,  2.3543526 ,  1.97815653],
       [-0.10390437, -1.32459816, -0.27560613,  1.38098633],
       [-1.85047963, -0.50731314,  1.2594663 ,  2.04497463],
       [ 1.05996073, -1.72905979, -0.43041594,  1.15811509],
       [ 2.5321193 , -2.23192823, -0.57215811,  0.88988629],
       [ 2.04471886, -2.26032683, -1.73238088,  0.67334163],
       [ 0.51106973, -1.60555672, -0.77392894,  1.15786377],
       [ 1.36596671, -1.73370821,  0.1587794 ,  1.25885047]])

In [7]:
def sigmoid(x):
  return 1 / (1+np.exp(-x))

In [9]:
a=sigmoid(h);a

array([[0.30759045, 0.23291829, 0.29265529, 0.79234904],
       [0.26609568, 0.24676887, 0.30532736, 0.80003279],
       [0.58112614, 0.26102871, 0.91327957, 0.87848451],
       [0.47404725, 0.2100543 , 0.43153132, 0.79914936],
       [0.13581659, 0.3758236 , 0.77893422, 0.88543885],
       [0.74268304, 0.15070788, 0.39402701, 0.76099005],
       [0.92636305, 0.09691974, 0.360739  , 0.70886671],
       [0.8854129 , 0.09446241, 0.15028329, 0.662251  ],
       [0.62505721, 0.16720642, 0.31562981, 0.76094433],
       [0.79672773, 0.15011387, 0.53961167, 0.77882816]])

In [12]:
W2 = np.random.randn(4,3); W2

array([[-1.37739058, -1.37091245,  1.02414928],
       [ 0.53476128, -0.57238529, -1.18448979],
       [ 0.78459979, -1.51697355, -0.88192149],
       [ 0.2837107 ,  0.82732871, -0.72231865]])

In [14]:
b2 = np.random.randn(3) ; b1

array([-0.08098443, -0.3624163 , -1.45582362])

In [16]:
s = np.matmul(a, W2) + b2;s # 10x3 3차원 데이터로 변환되었다는 의미 / 3개의 분류를 할 수 있음

array([[ 0.37118812, -0.25582204,  0.46471824],
       [ 0.44787185, -0.21973042,  0.38908963],
       [ 0.52083425, -1.51711378,  0.10200395],
       [ 0.24057675, -0.67597789,  0.53488725],
       [ 1.09215297, -0.76278842, -0.37657407],
       [-0.2014279 , -0.98496228,  0.94094466],
       [-0.52409655, -1.19861005,  1.25977899],
       [-0.64735516, -0.86037521,  1.44002741],
       [-0.09211181, -0.71426242,  0.8701091 ],
       [-0.15689965, -1.2648029 ,  0.85571906]])

In [17]:
# 완전연결계층에 의한 변환은 기하학에서의 아핀변환에 해당(Affine)
# 계층은 파이썬 클래스로 구현하며, 기본변환을 수행하는 메서드의 이름은 forward()
# 모든 계층은 forward() / backward()를 가짐
# 모든계층은 인스턴스 변수인 params / Grads를 가짐
# params : 가중치와 편향같은 매개변수를 담은 리스트
# grads : params에 저장된 각 매개변수에 대응하여 해당 매개변수의 기울기를 보관하는 리스트


In [5]:
import numpy as np
class Sigmoid:
  def __init__(self): 
    self.params = []
  
  def forward(self, x):
    return 1/ (1+np.exp(-x))
# 주변환처리는 forward(x) 메서드가 담당함


In [21]:
class Affine:
  def __init__(self, W,b):
    self.params = [W,b]
  
  def forward(self,x):
    W, b = self.params 
    out = np.matmul(x,W) + b
    return out
   # 초기화할때 가중치와 편향을 받음
   #  

In [9]:
# x-affine-sigmoid-affine-s 구현해보기

class TwoLayerNet:
  def __init__(self, input_size, hidden_size, output_size):
    I,H,O = input_size, hidden_size, output_size
    #가중치편향초기화
    W1 = np.random.randn(I, H)
    b1 = np.random.randn(H)
    W2 = np.random.randn(H,O)
    b2 = np.random.randn(O)

    #계층생성 / 3개의 계층을 생성함
    self.layers = [Affine(W1,b1), Sigmoid(), Affine(W2,b2)]

    # 모든 가중치를 리스트에 모은다
    self.params = []
    for layer in self.layers: 
      self.params += layer.params
  
  def predict(self, x):
    for layer in self.layers:
      x = layer.forward(x)
    return x

In [32]:
a = ['A', 'B']
a+= ['C','D']
a

['A', 'B', 'C', 'D']

In [33]:
x = np.random.randn(10,2)
model = TwoLayerNet(2,4,3)
s=model.predict(x)

In [34]:
s

array([[-1.50968998, -3.69145486, -0.59078053],
       [-1.6117588 , -4.22416638, -0.71167142],
       [-0.49862053, -2.90384628, -1.64117301],
       [-0.73843196, -2.6384056 , -0.9049674 ],
       [-0.96349443, -2.85194653, -0.70539678],
       [-0.42929553, -2.41121233, -1.55367667],
       [-1.5465118 , -3.96349097, -0.71224558],
       [-0.90985446, -3.14941086, -1.01884055],
       [-0.82460339, -2.64136731, -0.77112327],
       [-0.98907426, -3.44949816, -1.19451352]])

In [35]:
#학습되지 않은 신경망은 좋은추론을 해낼수없음
#학습을 먼저 수행하고, 그 학습된 매개변수를 이용해 추론을 수행하는 흐름이 일반적


In [36]:
# 손실함수 :학습이 얼마나 잘 되고 있는지를 알기 위한 척도, 신경망의 성능을 나타내는 척도로 손실을 사용
# 예측한 결과를 비교하여 예측이 얼마나 나쁜가를 산출한 단일값(스칼라)
# 교차엔트로피 오차(cross entropy error) : 예측한 확률과 정답레이블을 이요해 계산
#

In [37]:
# x-affine-sigmoid-affine-softmax-crossentropy-error-L 과정구현
# 소프트 맥스의 출력값은 0~1실수


In [ ]:
# 기울기 개념의 등장 : 수학에서 말하는 기울기와는 다름, 수학에서의 기울기는 벡터에 대한 미분으로 한정, 한편 딥러닝에서는 행렬이나 텐서에 대해서도 미분을 정의함
# 국소적인 미분을 구할수있다면 전체의 미분을 구할수있게하는 아이디어 : 연쇄법칙


In [ ]:
# 역전파 종류-
# 덧셈노드
# 곱셈노드
# 분기노드
# REPEAT노드(N개의 분기노드)
# SUM노드
# MATMUL노드

In [39]:
import numpy as np
D, N = 8,7
x = np.random.randn(1,D);x # 8 개랜덤값

array([[-0.5794089 , -0.4090421 ,  0.11616307, -0.80426539,  0.86277395,
        -0.22785349,  1.2346049 ,  0.36791626]])

In [40]:
y = np.repeat(x,N, axis=0); y # x를 N번 반복

array([[-0.5794089 , -0.4090421 ,  0.11616307, -0.80426539,  0.86277395,
        -0.22785349,  1.2346049 ,  0.36791626],
       [-0.5794089 , -0.4090421 ,  0.11616307, -0.80426539,  0.86277395,
        -0.22785349,  1.2346049 ,  0.36791626],
       [-0.5794089 , -0.4090421 ,  0.11616307, -0.80426539,  0.86277395,
        -0.22785349,  1.2346049 ,  0.36791626],
       [-0.5794089 , -0.4090421 ,  0.11616307, -0.80426539,  0.86277395,
        -0.22785349,  1.2346049 ,  0.36791626],
       [-0.5794089 , -0.4090421 ,  0.11616307, -0.80426539,  0.86277395,
        -0.22785349,  1.2346049 ,  0.36791626],
       [-0.5794089 , -0.4090421 ,  0.11616307, -0.80426539,  0.86277395,
        -0.22785349,  1.2346049 ,  0.36791626],
       [-0.5794089 , -0.4090421 ,  0.11616307, -0.80426539,  0.86277395,
        -0.22785349,  1.2346049 ,  0.36791626]])

In [41]:
dx = np.random.randn(N,D) ;dx.shape

(7, 8)

In [45]:
dy = np.sum(dx, axis=0, keepdims=True);dy #  keepdims=True : 2차원을 유지시킴
# (1,D) 출력 NOT (D)

array([[ 1.75530335,  2.4007671 ,  0.80061987,  3.1102779 ,  0.78699361,
         0.44033144,  1.3401611 , -2.93366021]])

In [46]:
dy.ndim

2

In [47]:
# SUM노드의 역전파
D,N = 8,7 
x=np.random.randn(N,D)
y=np.sum(x, axis=0, keepdims=True) 
dx = np.random.randn(1,D)
dy = np.repeat(dy, N, axis=0)

In [1]:
# matmul노드의 역전파
# y = xW
# (1,H) = (1,D) * (D,H) 
# (N,H) = (N,D) * (D,H) / 미니배치 처리인 경우



In [3]:
class MatMul:
  def __init__(self, W):
    self.params = [W]
    self.grads = [np.zeros_like(W)]
    self.x = None  
  
  def forward(self, x): 
    W, = self.params  
    out = np.matmul(x, W)
    self.x = x
    return out 
  
  def  backward(self, dout ):
    W, = self.params 
    dx = np.matmul(dout, W.T) 
    dy = np.matmul(self.x.T, dout )
    self.grads[0][...] = dW  # 기울기값 설정하는 부분, 생략기호 ... 사용. 넘파이 배열이 가리키는 메모리 위치를 고정시킨 다음, 그 위치에 원소들을 덮어씀
    # 생략기호는 넘파이 배열의 덮어쓰기를 수행
    # grads[0] =dw처럼 그냥 할당하면 얕은 복사가 이루어지고 grads[0][...]= dw처럼 덮어쓰면 깊은 복사가 이뤄짐
    return dx 

In [9]:
a = np.array([1,2,3])
b = np.array([4,5,6])
a=b;a

array([4, 5, 6])

In [8]:
a = np.array([1,2,3])
b = np.array([4,5,6])
a[...]=b;a

array([4, 5, 6])

In [11]:
# a에는 모두 [4,5,6]이 할당됨
# 두경우, A가 가리키는 메모리의 위치가 서로 다름
# 생략기호를 이요하여 변수의 메모리 주소를 고정할 수 있음
# 메모리 주소를 고정함으로써 인스턴스 변수 grads를 다루기가 더 쉬워짐
# grads리스트에는 각 매개변수의 기울기를 저장함. 생략기호를 사용하므로 이 넘파이 배열의 메모리 주소가 변하는 일 없이 항상 값을 덮어씀
# 이렇게 하면 기울기를 그룹화하는 작업을 최초에 한번만 하면 된다는 이점이 생김


In [12]:
# 기울기의 도출과 역전파 구현
# 1. sigmoid계층
class Sigmoid:
  def __init__(self):
    self.params , self.grads =[],[]
    self.out = None 
  
  def forward(self, x):
    out = 1/(1+np.exp(-x))
    self.out = out 
    return out 
  
  def backward(self, dout) : 
    dx = dout * (1-self.out) * self.out 
    return dx  
  

In [4]:
# affine 계층
# 순전파 : y=np.matmul(x,W)+b
# 편향을 더할때는 넘파이의 브로드캐스트가 사용됨
class Affine:
  def __init__(self,W,b):
    self.params = [W,b]
    self.grads = [np.zeros_like(W), np.zeros_like(b)]
    self.x = None

  def forward(self,x):
    W,b = self.params
    out = np.matmul(x,W) + b
    self.x = x
    return out 
  
  def backward(self, dout):
    W,b = self.params
    dx = np.matmul(dout, W.T) 
    dW = np.matmul(self.x.T, dout)
    db = np.sum(dout, axis = 0)
    self.grads[0][...] = dW 
    self.grads[1][...] = db 
    return dx 



In [5]:
# soft max with loss 계층
#소프트 맥스함수와 교차 엔트로피 오차는 하나의 계층으로 구현할 것


In [6]:
# SGD구현
class SGD:
  def __init__(self, lr=0.01):
    self.lr = lr
  
  def update(self, params, grads):
    for i in range(len(params)):
      params[i] -= self.lr * grads[i]
      

In [1]:
import sys
sys.path

['',
 '/content',
 '/env/python',
 '/usr/lib/python37.zip',
 '/usr/lib/python3.7',
 '/usr/lib/python3.7/lib-dynload',
 '/usr/local/lib/python3.7/dist-packages',
 '/usr/lib/python3/dist-packages',
 '/usr/local/lib/python3.7/dist-packages/IPython/extensions',
 '/root/.ipython']

In [5]:

sys.path.append('/content/deep-learning-from-scratch-2')

In [15]:
!pip install dataset

     |████████████████████████████████| 210 kB 5.2 MB/s 
     |████████████████████████████████| 75 kB 3.4 MB/s 


In [6]:
from dataset import spiral  

In [8]:
import matplotlib.pyplot as plt 
x,t = spiral.load_data()

print('x', x.shape)
print('t', t.shape)

x (300, 2)
t (300, 3)


In [10]:
from common.layers import Affine, Sigmoid, SoftmaxWithLoss

class TwoLayerNet:
  def __init__(self, input_size, hidden_size, output_size):
    I,H,O = input_size, hidden_size, output_size 
    #가중치와 편향초기화
    W1 = 0.01 * np.random.randn(I,H)
    b1 = np.zeros(H)
    W2 = 0.01 * np.random.randn(H,O)
    b2 = np.zeros(0)

    # 계층생성
    self.layers = [Affine(W1, b1), Sigmoid(), Affine(W2,b2)]
    self.loss_layer = SoftmaxWithLoss()

    # 모든 가중치와 기울기를 리스트에 모음
    self.params , self.grads = [], []
    for layer in self.layers : 
      self.params += layer.params
      self.grads += layer.grads 

  def predic(self, x):
    for layer in self.layers : 
      x = layer.forward(x)
    return x 
  

  def forward(self, x, t):
    score = self.predict(x)
    loss = self.loss_layer.forward(score,t)
    return loss  
  
  def backward(self, dout=1): 
    dout = self.loss_layer.backward(dout) 
    for layer in reversed(self.layers):
      dout = layer.backward(dout) 
    return dout 


In [ ]:
# 학습용 코드


# ch2. 자연어와 단어의 분산 표현 

In [11]:
# 단어의 의미 이해시키기
# 1. 시소러스를 활용한 기법(유의어 사전활용)
# 2. 통계 기반기법
# 3. 추론기반기법(word2vec)


In [13]:
# 1.시로러스 활용
# car=auto = automobile machine 
# 단어사이의 연결을 정의
# 단어 네트워크를 이용하여 컴퓨터에게 단어 사이의 관계를 가르침
# 워드넷 : 자연어 처리 분야에서 가장 유명한 시소러스/ 프린스턴 대학에서 1985년부터 구축하기 시작
# 유의어를 얻거나 단어 네트워크를 이용할 수 있음
# NLKT모듈을 설치하고 간단한 실험을 해볼예정
# 시소러스의 문제점 : 단어의 의미를 사람이 수작업으로 레이블링하는 방식 : 시대변화에 대응하기 어려움, 사람을 쓰는 비용이 큼, 단어의 미묘한 차이를 표현할 수 없음(레트로, 빈티지)


In [14]:
# 2.통계 기반 기법
# 말뭉치(CORPUS)
# 

In [15]:
# 파이썬으로 말뭉치 전처리하기
text= 'you say goodbye and i say hello.'
text=text.lower()
text= text.replace('.',' .')
text

'you say goodbye and i say hello .'

In [16]:
words = text.split(' ')

In [17]:
words

['you', 'say', 'goodbye', 'and', 'i', 'say', 'hello', '.']

In [19]:
word_to_id ={}
id_to_word = {}
for word in words:
  if word not in word_to_id:
    new_id = len(word_to_id) 
    word_to_id[word] = new_id 
    id_to_word[new_id] = word 

In [20]:
id_to_word

{0: 'you', 1: 'say', 2: 'goodbye', 3: 'and', 4: 'i', 5: 'hello', 6: '.'}

In [21]:
word_to_id

{'.': 6, 'and': 3, 'goodbye': 2, 'hello': 5, 'i': 4, 'say': 1, 'you': 0}